# Generated by Django 2.2.7 on 2021-09-01 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Autores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rotulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Rótulo',
                'verbose_name_plural': 'Rótulos',
                'ordering': ['titulo'],
            },
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['choice_text'], 'verbose_name': 'Opção', 'verbose_name_plural': 'Opções'},
        ),
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Data de Encerramento'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('cidade', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=100)),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Autor')),
            ],
            options={
                'verbose_name_plural': 'Informações de Perfil',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Autor'),
        ),
        migrations.AddField(
            model_name='question',
            name='rotulos',
            field=models.ManyToManyField(to='polls.Rotulo', verbose_name='Rótulos'),
        ),
    ]
